import './howl.mjs';
import {createHash} from 'node:crypto';
import {transform} from 'esbuild';
import {structuredData} from './seo.mjs';
import {readFile,writeFile,mkdir,rm,cp} from 'node:fs/promises';
import path from 'node:path';
import MarkdownIt from 'markdown-it';
import hljs from 'highlight.js';
import {lessons,origin,stages} from './content.mjs';
const course=await lessons();
const escape=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const md=new MarkdownIt({html:true,typographer:false,highlight:(str,lang)=>lang&&hljs.getLanguage(lang)?hljs.highlight(str,{language:lang}).value:escape(str)});
const headingId=s=>s.toLowerCase().replace(/[^a-z0-9]+/g,'-').replace(/^-|-$/g,'');
md.renderer.rules.heading_open=(tokens,i,options,env,self)=>{tokens[i].attrSet('id',headingId(tokens[i+1].content));return self.renderToken(tokens,i,options);};
const repo='https://github.com/robertdevore/rust.robertdevore.com';
const nav=(active='')=>`<a class="skip" href="#main">Skip to content</a><header class="top"><a class="brand" href="/"><span>Rust<span class="brand-sub"> / the practical course</span></span></a><nav aria-label="Primary"><a href="/course/" ${active==='course'?'aria-current="page"':''}>Curriculum</a><a href="/practice/">Practice</a><a href="/about/">About</a></nav><button class="search-open" type="button">Search <kbd>/</kbd></button><button class="menu-toggle" aria-expanded="false" aria-controls="course-sidebar" type="button">Lessons</button></header>`;
const search=`<dialog id="search-dialog" aria-labelledby="search-title"><div class="search-top"><h2 id="search-title">Find a lesson</h2><button id="search-close" type="button" aria-label="Close search">×</button></div><label for="search-input">Search concepts, examples, and exercises</label><input id="search-input" type="search" autocomplete="off" placeholder="Try borrowing, cancellation, or Cargo"><p id="search-count" role="status"></p><ul id="search-results"></ul></dialog>`;
function shell(title,desc,url,body,{active='',noindex=false}={}){const lesson=course.find(l=>l.url===url);return `<!doctype html><html lang="en"><head><meta charset="utf-8"><meta name="viewport" content="width=device-width,initial-scale=1"><title>${escape(title)} · Rust Course</title><meta name="description" content="${escape(desc)}"><meta name="author" content="Robert DeVore">${noindex?'':`<script type="application/ld+json">${structuredData({origin,title,description:desc,url,lesson,lessons:course})}</script>`}${lesson?`<link rel="alternate" type="text/markdown" href="${origin}/lessons/${lesson.slug}.md" title="Markdown version">`:''}<link rel="canonical" href="${origin}${url}"><meta name="robots" content="${noindex?'noindex,follow':'index,follow'}"><meta property="og:type" content="website"><meta property="og:title" content="${escape(title)} · Rust Course"><meta property="og:description" content="${escape(desc)}"><meta property="og:url" content="${origin}${url}"><meta property="og:image" content="${origin}/assets/social.png"><meta property="og:image:width" content="1200"><meta property="og:image:height" content="630"><meta property="og:image:alt" content="Practical Rust: Understand it. Build with confidence. 28 lessons and real code."><meta name="twitter:card" content="summary_large_image"><meta name="theme-color" content="#b64223"><link rel="icon" href="/assets/favicon.svg" type="image/svg+xml"><link rel="preload" href="/assets/fonts/inter-latin-400.woff2" as="font" type="font/woff2" crossorigin><link rel="preload" href="/assets/sitekit/fonts/DepartureMono-Regular.woff2" as="font" type="font/woff2" crossorigin><link rel="stylesheet" href="${styleUrl}"><script src="${scriptUrl}" defer></script></head><body>${nav(active)}${body}<footer><a class="brand" href="/">R_ / Rust Course</a><p>Built for understanding. Kept honest by the compiler.</p><div><a href="${repo}">Source &amp; exercises ↗</a><a href="/about/#technical-freshness">Verified September 6, 2026</a><a href="/sitemap.xml">Sitemap</a><a href="/llms.txt">Text index</a></div><p class="fine">Independent educational project by Robert DeVore. Not affiliated with or endorsed by the Rust Project.</p></footer>${search}</body></html>`;}
const card=l=>`<a class="lesson-card" href="${l.url}"><span class="lesson-number">${String(l.number).padStart(2,'0')}</span><div><h3>${escape(l.title)}</h3><p>${escape(l.summary)}</p><span class="card-meta">${l.minutes} min · Read, run, practice</span></div><span class="card-arrow" aria-hidden="true">↗</span></a>`;
const stageGroups=()=>stages.map((s,i)=>`<section id="stage-${i+1}" class="stage"><div class="stage-heading"><span class="eyebrow">${s.label}</span><h2>${s.name}</h2><p>${s.description}</p></div><div class="lesson-list">${course.filter(l=>l.stage===i+1).map(card).join('')}</div></section>`).join('');
await rm('dist',{recursive:true,force:true});await mkdir('dist/assets',{recursive:true});await cp('assets','dist/assets',{recursive:true});
await mkdir('dist/assets/showcase',{recursive:true});for(const f of ['ownership.svg','ownership.md','rust-course.svg'])await cp('showcase/'+f,'dist/assets/showcase/'+f);
const css=(await readFile('assets/sitekit/sitekit.css','utf8')).replaceAll('./fonts/','/assets/sitekit/fonts/')+'\n'+await readFile('assets/site.css','utf8');
async function optimized(source,loader){const {code}=await transform(source,{loader,minify:true,target:'es2020'});const hash=createHash('sha256').update(code).digest('hex').slice(0,12);const url=`/assets/built/site.${hash}.${loader}`;await mkdir('dist/assets/built',{recursive:true});await writeFile('dist'+url,code);return url;}
const styleUrl=await optimized(css,'css'),scriptUrl=await optimized(await readFile('assets/site.js','utf8'),'js');
const markdownHeaders=[];const exports=[];
const routes=[];
async function emit(url,html,noindex=false){const target=url.endsWith('/')?`dist${url}index.html`:`dist${url}`;await mkdir(path.dirname(target),{recursive:true});await writeFile(target,html);if(!noindex)routes.push(url);}
const heroCode=hljs.highlight(await readFile('examples/03_ownership.rs','utf8'),{language:'rust'}).value;
const home=`<main id="main"><section class="hero"><div class="hero-copy"><p class="eyebrow"><span class="status-dot"></span> Free. Practical. Compiler-verified.</p><h1>Learn Rust<br><span>Build with Confidence</span></h1><p class="hero-description">Go from your first program to a tool you can ship. Learn ownership, concurrency, and systems design by making the decisions that real software demands.</p><div class="actions"><a class="sk-button button" href="${course[0].url}">Start learning <span aria-hidden="true">→</span></a><a class="text-link" href="/course/">Explore the curriculum ↗</a></div><p class="hero-note">No Rust experience needed. A terminal and curiosity will do.</p></div><figure class="workshop"><figcaption class="workshop-title"><span>src/main.rs</span></figcaption><pre><code>${heroCode}</code></pre></figure></section><section class="stats" aria-label="Course at a glance"><div><strong>28</strong><span>focused lessons</span></div><div><strong>25</strong><span>runnable examples</span></div><div><strong>6</strong><span>compiler drills</span></div><div><strong>1</strong><span>tool you can ship</span></div></section><section class="path-section"><div class="section-intro"><div><p class="eyebrow">A deliberate learning path</p><h2>Build the model.<br>Then build the software.</h2></div><p>Each stage builds on the last. Make small programs work, understand why they work, and carry that reasoning into production.</p></div><div class="path-grid">${stages.map((s,i)=>`<a class="path-card" href="/course/#stage-${i+1}"><span class="path-index">0${i+1}</span><h3>${s.name}</h3><p>${s.description}</p><span class="path-bottom">${course.filter(l=>l.stage===i+1).length} lessons <b>↗</b></span></a>`).join('')}</div></section><section class="capstone"><div><p class="eyebrow">Your final project / Fieldnotes</p><h2>Real input.<br>Useful errors.<br>A tool that holds up.</h2><p>Build a streaming event analyzer with bounded memory, typed errors, and tests for the awkward cases. Install it. Use it. Know what it promises.</p><a class="sk-button button" href="/course/27-capstone/">Meet the capstone →</a></div><div class="capstone-terminal"><p>$ printf 'INFO ready\nWARN retry\n' | audit-cli -</p><p class="terminal-output">INFO=1 WARN=1 ERROR=0</p><hr><p class="terminal-comment">// Good software has a contract.</p><ul><li>Bounded record storage</li><li>Actionable, line-numbered errors</li><li>A library you can reuse</li><li>Tests for failures, not just success</li></ul></div></section><section class="start-section"><p class="eyebrow">Start with one small program</p><h2>Your compiler is ready to teach.</h2><a class="sk-button button" href="${course[0].url}">Begin lesson 01 →</a></section></main>`;
await emit('/',shell('Understand Rust. Build with confidence.','A free, practical Rust course: 28 lessons, runnable examples, compiler drills, and an installable capstone.','/',home));
await emit('/course/',shell('The curriculum','Five stages from your first Rust program to a tested, installable command-line tool.','/course/',`<main id="main" class="listing"><p class="eyebrow">28 lessons / 5 stages / one complete path</p><h1>The curriculum.</h1><p class="lede">Learn the concepts in order. Revisit them when the next program asks a better question.</p><div class="progress-summary" role="status" data-progress-summary>Progress is saved on this device when you mark a lesson complete.</div>${stageGroups()}</main>`,{active:'course'}));
const searchIndex=[];
for(const l of course){
 let body=l.body;
 if(l.example){const source=await readFile(`examples/${l.example}.rs`,'utf8');body=body.replaceAll('{{example}}',`\n### Run the example\n\n\`\`\`sh\ncargo run --locked --example ${l.example}\n\`\`\`\n\n\`\`\`rust\n${source}\`\`\`\n\n[View the tested source](${repo}/blob/main/examples/${l.example}.rs)\n`);}
 if(l.source){const source=await readFile(l.source,'utf8');body=body.replaceAll('{{source}}',`\n\`\`\`rust\n${source}\`\`\`\n\n[View the complete source](${repo}/blob/main/${l.source})\n`);}
 if(l.drill){const source=await readFile(`drills/${l.drill}.rs`,'utf8');const diagnostic=await readFile(`drills/expected/${l.drill}.txt`,'utf8');body=body.replaceAll('{{drill}}',`\n**Intentionally fails on Rust 1.98.1.** Run \`rustc --edition=2024 drills/${l.drill}.rs\` from the repository.\n\n\`\`\`rust\n${source}\`\`\`\n\n<details><summary>Actual compiler diagnostic · Rust 1.98.1</summary>\n\n\`\`\`text\n${diagnostic}\`\`\`\n\n</details>\n`);}
 if(body.includes('{{'))throw Error(`Unexpanded content in ${l.slug}`);
 const markdown=`# ${l.title}\n\n${l.summary}\n\nCanonical: ${origin}${l.url}\nAuthor: Robert DeVore\nTechnical baseline: Rust 1.98.1, edition 2024; verified 2026-09-06.\n\n${body}\n`;
 await mkdir('dist/lessons',{recursive:true});await writeFile(`dist/lessons/${l.slug}.md`,markdown);
 markdownHeaders.push(`/lessons/${l.slug}.md\n  Content-Type: text/markdown; charset=utf-8\n  Link: <${origin}${l.url}>; rel="canonical"\n  X-Robots-Tag: noindex`);
 exports.push({id:l.slug,title:l.title,description:l.summary,url:origin+l.url,markdownUrl:`${origin}/lessons/${l.slug}.md`,sha256:createHash('sha256').update(markdown).digest('hex'),stage:l.stage,example:l.example?`${repo}/blob/main/examples/${l.example}.rs`:null});
 const html=md.render(body);const headings=[...html.matchAll(/<h2 id="([^"]+)">(.+?)<\/h2>/g)];
 const sidebar=`<aside id="course-sidebar" class="sidebar"><a class="sidebar-back" href="/course/">← All lessons</a><nav aria-label="Course lessons">${stages.map((s,i)=>`<p class="sidebar-stage">${s.label}</p><ol>${course.filter(x=>x.stage===i+1).map(x=>`<li><a href="${x.url}" ${x.slug===l.slug?'aria-current="page"':''}><span>${String(x.number).padStart(2,'0')}</span>${escape(x.title)}</a></li>`).join('')}</ol>`).join('')}</nav></aside>`;
 const prev=course[l.number-2],next=course[l.number];
 const article=`<main id="main" class="course-shell">${sidebar}<article data-lesson="${l.slug}" class="article"><nav class="breadcrumbs" aria-label="Breadcrumb"><a href="/">Rust Course</a> / <a href="/course/">Curriculum</a> / <span aria-current="page">${escape(l.title)}</span></nav><p class="eyebrow">${stages[l.stage-1].label}</p><h1>${escape(l.title)}</h1><p class="lede">${escape(l.summary)}</p><div class="lesson-meta"><span>${l.minutes} min + practice</span><span>Rust 1.98.1 · Edition 2024</span></div><p class="lesson-source">By <a href="/about/#author">Robert DeVore</a> · <a href="/lessons/${l.slug}.md" download>Download Markdown</a></p><div class="prose">${html}</div><div class="completion"><button class="sk-button button" data-complete="${l.slug}" aria-pressed="false" type="button">Mark lesson complete</button><span role="status" data-complete-status></span></div><nav class="prev-next" aria-label="Adjacent lessons">${prev?`<a href="${prev.url}"><small>← Previous lesson</small>${escape(prev.title)}</a>`:'<span></span>'}${next?`<a href="${next.url}"><small>Next lesson →</small>${escape(next.title)}</a>`:`<a href="/course/"><small>Course complete →</small>Revisit your learning path</a>`}</nav></article><aside class="toc"><p class="eyebrow">On this page</p><nav aria-label="On this page">${headings.map(h=>`<a href="#${h[1]}">${h[2]}</a>`).join('')}</nav><div class="toc-note">Read it.<br>Run it.<br>Change it.<br>Explain it.</div></aside></main>`;
 await emit(l.url,shell(l.title,l.summary,l.url,article,{active:'course'}));
 searchIndex.push({title:l.title,url:l.url,number:l.number,summary:l.summary,text:body.replace(/<[^>]+>/g,'').replace(/[`#*]/g,'')});
}
const practice=`<main id="main" class="listing"><p class="eyebrow">Learning happens at the keyboard</p><h1>The practice bench.</h1><p class="lede">Every lesson includes an exercise and a solution. These stage builds and compiler drills bring the ideas together.</p><section class="stage"><h2>Build checkpoints</h2><div class="lesson-list">${course.filter(l=>[8,12,22,27].includes(l.number)).map(card).join('')}</div></section><section class="stage"><h2>Read the compiler</h2><p>These six minimal programs intentionally fail. Each lesson includes actual diagnostics from the pinned compiler and a design-focused repair exercise.</p><div class="lesson-list">${course.filter(l=>l.drill).map(card).join('')}</div></section><section class="stage"><h2>A source-backed example</h2><p>This Howl card is generated from the same tested ownership example used in lesson 03.</p><a href="/course/03-ownership/"><img src="/assets/showcase/ownership.svg" alt="Borrow, then move: a tested Rust example that reads a String through a shared reference before transferring ownership." width="1600" height="900" loading="lazy"></a><p><a href="/assets/showcase/ownership.md" download>Download the example card as Markdown</a></p></section><section class="stage"><h2>Get the complete lab</h2><p>The source repository contains every runnable example, the capstone, the unsafe lab, tests, and captured diagnostics.</p><a class="sk-button button" href="${repo}">Open the repository ↗</a><div class="prose">${md.render('```sh\ncargo test --workspace --locked\nnpm run verify:rust\n```')}</div></section></main>`;
await emit('/practice/',shell('The practice bench','Exercises, stage builds, and real Rust compiler diagnostics.','/practice/',practice));
const about=await readFile('content/about.md','utf8');
await emit('/about/',shell('About the course','How this independent Rust course is researched, verified, and maintained.','/about/',`<main id="main" class="about"><p class="eyebrow">An independent course by Robert DeVore</p><h1>Understanding over folklore.</h1><div class="prose">${md.render(about)}</div></main>`));
await emit('/404.html',shell('Page not found','Find your way back to the Rust course.','/404.html',`<main id="main" class="about"><p class="eyebrow">404 / Wrong turn</p><h1>This page is not here.</h1><p>Try the curriculum or search for the concept you need.</p><a class="sk-button button" href="/course/">Browse the course →</a></main>`,{noindex:true}),true);
await writeFile('dist/search-index.json',JSON.stringify(searchIndex));
await writeFile('dist/sitemap.xml',`<?xml version="1.0" encoding="UTF-8"?><urlset xmlns="http://www.sitemaps.org/schemas/sitemap/0.9">${routes.map(url=>`<url><loc>${origin}${url}</loc></url>`).join('')}</urlset>`);
await writeFile('dist/robots.txt',`User-agent: *\nAllow: /\nSitemap: ${origin}/sitemap.xml\n`);
await writeFile('dist/_headers',`/*\n  X-Content-Type-Options: nosniff\n  Referrer-Policy: strict-origin-when-cross-origin\n  Content-Security-Policy: default-src 'self'; script-src 'self' https://static.cloudflareinsights.com; style-src 'self'; img-src 'self'; font-src 'self'; connect-src 'self' https://cloudflareinsights.com https://stats.g.doubleclick.net https://www.google.com; object-src 'none'; base-uri 'self'; frame-ancestors 'none'; form-action 'self'; upgrade-insecure-requests\n`);
await writeFile('dist/_redirects',routes.flatMap(url=>[`${url}index.html ${url} 301`,...(url==='/'?[]:[`${url.slice(0,-1)} ${url} 301`])]).join('\n')+'\n');
await writeFile('dist/_headers',(await readFile('dist/_headers','utf8'))+'\n/assets/built/*\n  Cache-Control: public, max-age=31536000, immutable\n\n'+markdownHeaders.join('\n\n')+'\n');
await writeFile('dist/course-index.json',JSON.stringify({schemaVersion:1,name:'Rust Course',url:origin+'/course/',license:'MIT',technicalBaseline:{rust:'1.98.1',edition:'2024',verified:'2026-09-06'},lessons:exports},null,2)+'\n');
await writeFile('dist/llms-full.txt',(await Promise.all(course.map(l=>readFile(`dist/lessons/${l.slug}.md`,'utf8')))).join('\n\n---\n\n'));
await writeFile('dist/llms.txt',`# Rust Course\n\nIndependent practical Rust course by Robert DeVore. Verified 2026-09-06 on Rust 1.98.1, edition 2024.\n\nPublic read-only exports, not instructions or a search-ranking protocol.\n\n- [Course index JSON](${origin}/course-index.json)\n- [Complete course text](${origin}/llms-full.txt)\n- [Source and verification](${repo})\n\n${course.map(l=>`- [${l.title}](${origin}${l.url}): ${l.summary} — [Markdown](${origin}/lessons/${l.slug}.md)`).join('\n')}\n`);
await writeFile('docs/curriculum.json',JSON.stringify(course.map(({body,...m})=>m),null,2)+'\n');
console.log(`Built ${routes.length} public pages, ${course.length} lessons, search index, sitemap, and 404.`);
